.PHONY: all figures

all: figures

figures:
	python3 plot_wavenumber_modulation.py
	python3 plot_gravity_modulation.py
	python3 plot_frequency_modulation.py
	python3 plot_amplitude_modulation.py
	python3 plot_numerical_simulations.py
	python3 plot_numerical_simulations_ramp_properties.py
